baseURL = '/'
languageCode = 'en-us'
title = 'Bob Rockefeller'
theme = 'roadster'

# Configure Pagination. See https://gohugo.io/templates/pagination/#configuration
[pagination]
  pagerSize = 4 # (int) The number of pages per pager. Default is 10

[Params]
  description = "Bob Rockefeller's General Blog" # Site description. Used in meta description
  copyright = "Bob Rockefeller" # Footer copyright holder, otherwise will use site title
  readmore = false # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["date", "categories"]
  customCSS = ["/css/lightbox.css", "/css/custom.css"] # Include custom CSS files
  customJS = ["/js/lightbox.js"] # Include custom JS files

[params.author]
  name = "Bob Rockefeller"
  bio = "What is Bob up to now?"
  avatar = "img/avatar.png"

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["categories", "taglist", "social"]

[Params.widgets]
  recent_num = 3 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget


[Params.widgets.social]
  cached = true # activate cache if true
  # Enable parts of social widget
  facebook = "bob.rockefeller"
  x = "BobRockefeller"
  instagram = "bobrockef"
  email = "bob@bobrockefeller.com"


[taxonomies]
  tag = "tags"
  category = "categories"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

  # [[menu.main]]
  #   name = "Portfolio"
  #   url = "/portfolio/"
  #   weight = 5

  # [[menu.main]]
  #   name = "Nature"
  #   url = "/services/web-development/"
  #   parent = "Portfolio"
  #   weight = 1

  # [[menu.main]]
  #   name = "People"
  #   url = "/services/seo/"
  #   parent = "Portfolio"
  #   weight = 2

  # [[menu.main]]
  #   name = "Places"
  #   url = "/services/web-development/ecommerce/"
  #   parent = "Portfolio"
  #   weight = 3

  # [[menu.main]]
  #   name = "Pets"
  #   url = "/services/web-development/custom-apps/"
  #   parent = "Portfolio"
  #   weight = 4
